### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by VictorMourthe** [devicehive/devicehive-audio-analysis#2]
Hello! Great work!

I'm new in audio analysis and tensorflow...

How i change the dataset? 

I want to use a offline dataset in my computer(Example: Urbansound). I can train this dataset and use it in place of youtube-8M?

Thanks!

**Comment by VictorMourthe** [comment]
I found the solution for this... 
Sorry for this question.

**Comment by Wild1234** [comment]
@Vareko how did you do it?
